### ISSUE TITLE
Bài tập nhóm

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/INT2208-4-2018#145]
- Lập kế hoạch và thực hiện dần cả tài liệu dự án song song với lập trình phần mềm.
- Lập các tài liệu của dự án phần mềm của nhóm. 
- Viết báo cáo dự án của nhóm trên Google Docs. Tất cả các thành viên cần tham gia thực hiện.  Tham khảo để làm báo cáo [KLTN](https://docs.google.com/document/d/1L-oWQRV5b8ALB6W0ETsTovWxty0flvVQHw26k5st3eY/edit?usp=sharing).

**Comment by jindojojin** [comment]
em thưa thầy là ý thứ 2 thầy viết có khác ý thứ 3 không ạ ? theo như trên lớp thầy nói thì  em chỉ biết có 2 việc phải làm là lập kế hoặc làm việc ( ý 1) và làm tài liệu dưới dạng báo cáo ( ý 3) ạ. Mong thầy trả lời giúp em, em xin cảm ơn ạ.

**Comment by truonganhhoang** [comment]
ý 2 và 3 đều là 1 tài liệu báo cáo, mô tả dự án của nhóm.
