### ISSUE TITLE
Tự đánh giá và chấm điểm chéo

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/INT2208-4-2018#181]
1. Mỗi bạn làm báo cáo tổng kết trong môn học này đã làm các bài tập cá nhân, bài tập nhóm, và tham gia tự học được đến đâu. Báo cáo cần kèm theo minh chứng bằng các url đến tài liệu, thông tin để dễ dàng kiểm tra, xác minh được. Hạn là trong ngày 12/5/2018. Báo cáo được đặt tên là: tongket.md đặt trong thư mục của mỗi người.

2. Mỗi bạn chấm điểm 4 bạn sinh viên ở dưới mình trong danh sách. Các bạn ở cuối danh sách thì quay lên đầu danh sách cho đủ 4 bạn. Các bạn cũng bỏ qua các bạn đã bỏ học, không có bài để chấm, không liên lạc được. Khi chấm, các bạn có thể trao đổi với bạn được chấm đề làm rõ việc tham gia làm bài tập về nhà, bài tập nhóm đến được đến đâu. Các bạn chấm điểm xong ghi điểm vào Excel, đồng thời ghi điểm vào cuối file tongket.md của bạn được chấm. Ghi rõ các thông tin:
   - Người chấm: 
   - Điểm:
   - Nhận xét: 
Hạn cho việc này là 13/5/2018.

3. Các bạn hoàn thành [khóa học](https://www.edx.org/course/software-engineering-introduction-ubcx-softeng1x) và có chứng chỉ hoàn thành (làm hết bài kiểm tra cuối cùng) thì chia sẻ link chứng chỉ, chụp ảnh đưa vào thư mục của mình trên repo và được cộng thêm 2.0 điểm vào điểm thành phần (quá 10 thì làm tròn về 10). Hạn cuối cùng để nộp bài là 20/5/2018.

4. 16/5/2018 là hạn hoàn thành bài tập lớn. Từ 17/5/2018 giáo viên sẽ chấm bài tập lớn.

**Comment by hoanganhit1997** [comment]
Em thưa thầy 1 người chấm điểm cho 4 người thì ghi vào cột chấm chéo trong excel như thế nào được ạ.

**Comment by truonganhhoang** [comment]
Các em chấm chéo và điền điểm chấm chéo vào gsheet.

**Comment by truonganhhoang** [comment]
Khi tạo pull request, các bạn nộp qua nhóm cho đỡ bị conflicts, nộp điểm vào repo của nhóm trưởng, rồi nhóm trưởng tạo pull request lên repo chính.
