### ISSUE TITLE
nhóm 4 đã sửa lỗi conflict và tạo lại pull request update tài liệu

### ISSUE THREAD

**Issue by jindojojin** [truonganhhoang/INT2208-4-2018#454]
Nhóm em đã sửa được lỗi conflict và tạo lại pull request đã bị hủy trước đó, mong thầy có thể merge và chấm thêm phần tài liệu của nhóm em ạ, em xin cảm ơn!

**Comment by truonganhhoang** [comment]
pull của nhóm em xóa hết cả lớp nên mình phải undo rồi

**Comment by minhnguyet206** [comment]
em đã sửa lại pull request cho bạn rồi ạ, mong thầy merge cho nhóm bọn em ạ , em cảm ơn thầy.

**Comment by truonganhhoang** [comment]
ok
