### ISSUE TITLE
Hỏi về cấu trúc phần thi tự luận

### ISSUE THREAD

**Issue by tuanlinhtl17** [truonganhhoang/INT2208-4-2018#457]
Em thưa thầy, phần thi tự luận của đề thi có dạng câu hỏi như thế nào ạ ? Vì lớp mình thi riêng nên bọn em vẫn thắc mắc phần nầy ạ ! Em cám ơn thầy.

**Comment by truonganhhoang** [comment]
Các em nắm được kiến thức trong tài liệu tiếng Việt mình đã tóm tắt là làm được bài. Câu hỏi tự luận cũng chỉ kiếm tra các khái niệm, nguyên lý, có khả năng lấy ví dụ. Có thể tham khảo bài kiểm tra của khóa học MOOC:
![image](https://user-images.githubusercontent.com/711995/40573671-ed4c00fa-60ee-11e8-8490-a3ca594c576c.png)
