### ISSUE TITLE
merge pull-request problem

### ISSUE THREAD

**Issue by phamngocduy98** [truonganhhoang/INT2208-4-2018#72]
Lỗi là tại em ạ!

Em có xóa 1 vài thư mục của các bạn tạo trong repo mà em fork về ạ
nên sau khi pull vào repo của lớp bị mất thư mục của các bạn ấy:
~~folder 16021400_nguyen_tuan_linh
~~folder NguyenHoangAnh
~~folder NguyenManhDung
~~folder NguyenVanPhi
~~folder TranQuangLinh
~~file DinhThiThuyDung
~~file README.md

Phát hiện này là của bạn Phi có nhắn cho em.
Em thật sự xin lỗi thầy và các bạn.

Thầy có thể phục hồi hoặc hướng dẫn em phục hồi được không ạ?
Em cảm ơn thầy ạ

**Comment by truonganhhoang** [comment]
Em nghiên cứu và dùng lệnh này nhé:

https://git-scm.com/docs/git-revert
https://backlog.com/git-tutorial/vn/stepup/stepup7_2.html

2018-02-07 14:53 GMT+07:00 Phạm Ngọc Duy - bautroixa.cf <
notifications@github.com>:

**Comment by phamngocduy98** [comment]
vâng em cảm ơn thầy ạ

**Comment by phamngocduy98** [comment]
Em thử revert nó cứ báo lỗi ạ.
do làm sai cách, git bash của em bị lỗi luôn.
Em quyết định upload lại các file lên như cũ ạ
